### ISSUE TITLE
not an arrow function

### ISSUE THREAD

**Issue by tj-commits** [IonicaBizau/noop6#13]
In GitHub, noop6 exports an arrow function, but [if u go to the code tab in NPM](https://www.npmjs.com/package/noop6?activeTab=code) and cd into lib/index.js, it exports  a regular function declaration.

**Comment by IonicaBizau** [comment]
Yes, because the code is transpiled.

**Comment by tj-commits** [comment]
Okay. But that's kind of misleading because in the npm package it says "using an arrow function"
