### ISSUE TITLE
Excuse me?...

### ISSUE THREAD

**Issue by makixx** [IonicaBizau/noop6#8]
`cb = cb || require("noop6");` can just be... `cb = cb || (()=>{});`

I'm sorry but this is actually really really embarrassing. Who in the right mind decides this is worth to be on npm. Regardless, I'm more surprised how often it is installed and used. You used it in your "tinyreq" library which makes it... less tiny?? I don't understand what the hell you were thinking. Also what is wrong with with the 850 weekly downloads. Are you trying to get famous with a (()=>{}) module?

It's like: to someone like me, I can remember things like :(){:|:&};: by heart and so I just don't get it... I think you should deprecate this and change the npm page such that it EXPLAINS to people that you're returning an empty function. Perhaps that way we can all learn how to script in Node.js better...

Also you're already on version 1.0.7... how do you even do that...

<img src="https://user-images.githubusercontent.com/8362329/41813835-b9a29586-7735-11e8-87d2-d32cf77b7960.png" width="400" height="300">

<img src="https://user-images.githubusercontent.com/8362329/41813837-bd5924ec-7735-11e8-9b62-aa0a53ed54b0.png" width="400" height="300">

**Comment by IonicaBizau** [comment]
> Also what is wrong with with the 850 weekly downloads. Are you trying to get famous with a (()=>{}) module?

You said so. Of course it makes me so famous. 🙈

**Comment by makixx** [comment]
I think you should read this regardless of what you're thoughts are:
https://thenewstack.io/node-js-creator-blasts-node-js-offers-a-secure-typescript-based-alternative/
